# Generated by Django 4.2.7 on 2025-09-15 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit')], db_index=True, max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='tracking_us_user_id_f7c12c_idx'), models.Index(fields=['event_type', 'timestamp'], name='tracking_us_event_t_7e73d5_idx')],
            },
        ),
    ]
