# Generated by Django 4.2.7 on 2025-09-16 01:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('source', models.CharField(choices=[('kafka', 'Kafka'), ('api', 'API'), ('mock', 'Mock')], default='api', max_length=10)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_data', models.JSONField(default=dict)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('user_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.userevent')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='tracking_me_status_cb20b8_idx'), models.Index(fields=['source', 'status'], name='tracking_me_source_103717_idx'), models.Index(fields=['user_id', 'queued_at'], name='tracking_me_user_id_375fd0_idx')],
            },
        ),
    ]
